name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macOS-12
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/setup-node@v3
      - run: npm install wasm-opt -g
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install nightly toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
          target: wasm32-unknown-unknown
          components: rust-src, rustfmt
          cache: true
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Install cargo-contract cargo-dylint dylint-link
        run: |
          cargo install cargo-dylint dylint-link
          cargo install cargo-contract --force --locked
      - name: Output versions
        run: |
          wasm-opt --version
          cargo -vV
          cargo contract --version
      - name: Build and Test simple-timed-lock
        run: |
          cargo +nightly contract build --verbose --manifest-path ./simple-timed-lock/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./simple-timed-lock/Cargo.toml
      - name: Build and Test single-secret-discovery
        run: |
          cargo +nightly contract build --verbose --manifest-path ./single-secret-discovery/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./single-secret-discovery/Cargo.toml
      - name: Build and Test many-secrets-discovery
        run: |
          cargo +nightly contract build --verbose --manifest-path ./many-secrets-discovery/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./many-secrets-discovery/Cargo.toml
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: target/ink/*.contract
