name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/setup-node@v3
      - run: npm install wasm-opt -g
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Install nightly toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly-2023-03-01
          target: wasm32-unknown-unknown
          components: rust-src, rustfmt, contract, cargo-dylint, dylint-link
          cache: true
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Output versions
        run: |
          wasm-opt --version
          cargo -vV
          cargo contract --version
          date >toolversions
          wasm-opt --version >>toolversions
          cargo -vV >>toolversions
          cargo contract --version >>toolversions
      - name: Build and Test simple-timed-lock
        run: |
          cargo +nightly contract build --verbose --manifest-path ./simple-timed-lock/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./simple-timed-lock/Cargo.toml
      - name: Build and Test single-secret-discovery
        run: |
          cargo +nightly contract build --verbose --manifest-path ./single-secret-discovery/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./single-secret-discovery/Cargo.toml
      - name: Build and Test many-secrets-discovery
        run: |
          cargo +nightly contract build --verbose --manifest-path ./many-secrets-discovery/Cargo.toml
          cargo +nightly contract test --verbose --manifest-path ./many-secrets-discovery/Cargo.toml
      - name: Check Events
        run: |
           pwd
           ./scripts/checkevents.sh
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             target/ink/**/*.contract
             toolversions
