name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Output versions
        run: |
          cargo -vV
          date >toolversions
          cargo -vV >>toolversions
      # - name: Build many-secrets-discovery
      #   uses: simonsso/cargo-contract@v0.0.3
      #   with:
      #     working-directory: many-secrets-discovery
      #     cargo-cmd: build --verbose --release
      - name: Test many-secrets-discovery
        uses: simonsso/cargo-contract@v0.0.3
        with:
          working-directory: many-secrets-discovery
          cargo-cmd: test --verbose
      - name: Build simple-timed-lock
        uses: simonsso/cargo-contract@v0.0.3
        with:
          working-directory: simple-timed-lock
          cargo-cmd: build --verbose --release
      - name: Test simple-timed-lock
        uses: simonsso/cargo-contract@v0.0.3
        with:
          working-directory: simple-timed-lock
          cargo-cmd: test --verbose
      - name: Build single-secret-discovery
        uses: simonsso/cargo-contract@v0.0.3
        with:
          working-directory: single-secret-discovery
          cargo-cmd: build --verbose
      - name: Test single-secret-discovery
        uses: simonsso/cargo-contract@v0.0.3
        with:
          working-directory: single-secret-discovery
          cargo-cmd: test --verbose      
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             */target/ink/**/*.contract
             target/ink/**/*.contract
             toolversions
