name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install cargo-contract
      run: |
        rustup install nightly
        rustup default nightly
        cargo install cargo-dylint dylint-link
        cargo install --force --locked cargo-contract

    - name: Build and Test simple-timed-lock
      run: |
        cd simple-timed-lock
        cargo contract build
        cargo contract test

    - name: Build and Test single-secret-discovery
      run: |
        cd single-secret-discovery
        cargo contract build
        cargo contract test

    - name: Build and Test many-secrets-discovery
      run: |
        cd many-secrets-discovery
        cargo contract build
        cargo contract test
