name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Output versions
        run: |
          cargo -vV
          date >toolversions
          wasm-opt --version >>toolversions
          cargo -vV >>toolversions
      - name: Build simple-timed-lock
        uses: simonsso/cargo-contract@master
        with:
          working-directory: /simple-timed-lock
          cargo-cmd: build
      # - name: Test simple-timed-lock
      #     uses: simonsso/cargo-contract
      #     with:
      #       working-directory: /simple-timed-lock
      #       cargo-cmd: test
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             */target/ink/**/*.contract
             toolversions
