name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  buildtest:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Output versions
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          cargo-cmd: versions.sh
      - name: Test many-secrets-discovery
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: many-secrets-discovery
          cargo-cmd: cargo test --verbose
      - name: Build many-secrets-discovery
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: many-secrets-discovery
          cargo-cmd: cargo contract build --verbose --release
      - name: Build simple-timed-lock
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: simple-timed-lock
          cargo-cmd: cargo contract build --verbose --release
      - name: Test simple-timed-lock
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: simple-timed-lock
          cargo-cmd: cargo test --verbose
      - name: Build single-secret-discovery
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: single-secret-discovery
          cargo-cmd: cargo contract build --verbose  --release
      - name: Test single-secret-discovery
        uses: open-actions-rs/action-cargo@v2.0.0
        with:
          working-directory: single-secret-discovery
          cargo-cmd: cargo test --verbose
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             */target/ink/**/*.contract
             target/ink/**/*.contract
             toolversions
