name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v3
      - name: Install stable toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
      - name: Check format
        uses: actions-rust-lang/rustfmt@v1
      - name: Output versions
        run: |
          cargo -vV
          date >toolversions
          cargo -vV >>toolversions
  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # fail-fast: false
        bins:
          - many-secrets-discovery
          - simple-timed-lock
          - single-secret-discovery
    steps:
      - name: Build ${{matrix.bins}}
        uses: simonsso/cargo-contract@v0.0.3
        with:
          cargo-cmd: build --verbose --manifest-path ./${{matrix.bins}}/Cargo.toml
      - name: Test ${{matrix.bins}}
        uses: simonsso/cargo-contract@v0.0.3
        with:
          cargo-cmd: test --verbose --manifest-path ./${{matrix.bins}}/Cargo.toml
  collect:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: contracts
          path: |
             */target/ink/**/*.contract
             target/ink/**/*.contract
             toolversions
