name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Ink
      run: |
        cargo install cargo-dylint dylint-link
        cargo install --force --locked cargo-contract
    - name: Build
      run: cargo contract build --verbose
    - name: Run tests
      run: cargo contract test --verbose
