name: Build and Test Smart Contracts

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: macos-latest
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/setup-node@v3
      - run: npm install wasm-opt -g
      - uses: actions/checkout@v3
      - name: Install toolchain
        id: toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rust-src
          override: true
      - name: Install cargo-contract cargo-dylint dylint-link
        run: |
          cargo install cargo-dylint dylint-link
          cargo install cargo-contract --force --locked
      - name: Output versions
        run: |
          wasm-opt --version
          cargo -vV
          cargo contract --version
      - name: Build and Test simple-timed-lock
        run: |
          cargo contract build --verbose --manifest-path ./simple-timed-lock/Cargo.toml
          cargo contract test --verbose --manifest-path ./simple-timed-lock/Cargo.toml
      - name: Build and Test single-secret-discovery
        working-directory: ./single-secret-discovery
        run: |
          cargo contract build --verbose --manifest-path ./single-secret-discovery/Cargo.toml
          cargo contract test --verbose --manifest-path ./single-secret-discovery/Cargo.toml
      - name: Build and Test many-secrets-discovery
        working-directory: ./many-secrets-discovery
        run: |
          cargo contract build --verbose --manifest-path ./many-secrets-discovery/Cargo.toml
          cargo contract test --verbose --manifest-path ./many-secrets-discovery/Cargo.toml